config/routes.rb
Stardust::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :states, only: [:index]
      resources :cities, only: [:index]
    end

    match 'v:api/*path', to: redirect('/api/v1/%{path}')
    match '*path', to: redirect('/api/v1/%{path}')
  end

  post "register" => "users#create", :as => "register"
  post "login" => "sessions#create", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users
  resources :posts

  get '/register',  to: 'identities#new',  as: 'register'
  get '/login',     to: 'sessions#new',    as: 'login'

  match '/auth/:provider/callback', to: 'sessions#create',  via: [:post, :get]
  match '/auth/failure',            to: 'sessions#failure', via: [:post, :get]

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stardust</title>
  <%= stylesheet_link_tag    "bootstrap.min", :media => "all" %>
  <%= javascript_include_tag "jquery-1.8.2.min.js" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= csrf_meta_tags %>
</head>

<body style="padding-top:40px;">

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="brand" href="/">Stardust</a>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
    <% if current_user.nil? %>
      <!-- <span id="login" class="navbar-link" style="cursor:pointer;">Login</span> -->
      <span><%= link_to 'Login', login_path -%></span>
      <span>|</span>
      <!-- <span id="register" class="navbar-link" style="cursor:pointer;">Register</span> -->
      <span><%= link_to 'Register', register_path -%></span>
    <% else %>
      <span id="create_post" class="navbar-link" style="cursor:pointer;">Create Post</span>
      <span id="username" class="navbar-link" style="cursor:pointer;"><%= current_user.username %></span>
      <span>|</span>
      <span id="logout" class="navbar-link" style="cursor:pointer;">Logout</span>
    <% end %>
        </p>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<%= debug flash %>

<div class="container-fluid">
  <div class="row-fluid">
    <%= yield %>
  </div>
</div>

<%= Rails.cache.fetch 'views/sessions/login_view' do render :partial => '/sessions/login' end %>

<%= Rails.cache.fetch 'views/sessions/register_view' do render :partial => '/sessions/register' end %>

<script>
  $(document).ready(function () {
  });

  $("#login").click(function() {
      $("#login_view").modal();
  });

  $("#logout").click(function() {
      location.href = "logout";
  });

  $("#register").click(function() {
      $("#register_view").modal();
  });

  $("#create_post").click(function() {
      location.href = "<%= new_post_path %>";
  });
</script>
<%= javascript_include_tag 'application' %>
</body>
</html>